platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
project 'TableViewPopoverPresenting.xcodeproj'

inhibit_all_warnings!
use_frameworks!

target 'TableViewPopoverPresenting_Example' do
  pod 'TableViewPopoverPresenting', :path => '../'
end
