platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
project 'TableViewPopoverPresenting.xcodeproj'

inhibit_all_warnings!
use_frameworks!

target 'TableViewPopoverPresenting_Example' do
  pod 'TableViewPopoverPresenting', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'

  target 'TableViewPopoverPresenting_UITests' do
    inherit! :search_paths
  end
end
