source 'https://github.com/CocoaPods/Specs.git'

project "TableViewPopoverPresenting.xcodeproj"

use_frameworks!

target 'TableViewPopoverPresenting_Example' do
  pod 'TableViewPopoverPresenting', :path => '../'

  target 'TableViewPopoverPresenting_Tests' do
    inherit! :search_paths

    pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => "swift-3.0"
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => "swift-3.0"
  end
end
