script:
- set -o pipefail && xcodebuild test -workspace Example/TableViewPopoverPresenting.xcworkspace -scheme TableViewPopoverPresenting-Example -destination "platform=iOS Simulator,id=85AF1F51-F2EB-4A4D-930B-0E5761511A45,name=iPhone SE,OS=10.3.1" -destination-timeout 1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

language: objective-c
xcode_workspace: Example/TableViewPopoverPresenting.xcworkspace
xcode_scheme: TableViewPopoverPresenting-Example
osx_image: xcode8.3
