osx_image: xcode8.1
language: objective-c
script:
- set -o pipefail && xcodebuild test -workspace Example/TableViewPopoverPresenting.xcworkspace -scheme TableViewPopoverPresenting-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
