script:
- set -o pipefail && xcodebuild test -workspace Example/TableViewPopoverPresenting.xcworkspace -scheme TableViewPopoverPresenting-Example -destination "platform=iOS Simulator,name=iPhone SE,OS=10.3.1" -destination-timeout 1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

language: objective-c
xcode_scheme: TableViewPopoverPresenting-Example
osx_image: xcode8.2
