osx_image: xcode8.1
language: objective-c
script:
- set -o pipefail && xcodebuild test -workspace Example/TableViewPopoverPresenting.xcworkspace -scheme TableViewPopoverPresenting_Example -destination "platform=iOS Simulator,name=iPhone SE,OS=10.1" -destination-timeout 1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
